apiVersion: v1
kind: Service
metadata:
  name: ethereum-service
spec:
  selector:
    app: ethereum-node
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
  type: LoadBalancer # Vous pouvez utiliser "NodePort" ou "ClusterIP" en fonction de vos besoins
